// Copyright (C) Dmytro Stechenko
// License: http://www.gnu.org/licenses/gpl.html

#ifndef ASM_AARCH64_BOOT_ENTRY_H
#define ASM_AARCH64_BOOT_ENTRY_H

#define ENTRY_STACK_FRAME_SIZE 256

#define ENTRY_SYN_INVALID_EL1t 0
#define ENTRY_IRQ_INVALID_EL1t 1
#define ENTRY_FIQ_INVALID_EL1t 2
#define ENTRY_ERR_INVALID_EL1t 3

#define ENTRY_SYN_INVALID_EL1h 4
#define ENTRY_IRQ_INVALID_EL1h 5
#define ENTRY_FIQ_INVALID_EL1h 6
#define ENTRY_ERR_INVALID_EL1h 7

#define ENTRY_SYN_INVALID_EL0_64 8
#define ENTRY_IRQ_INVALID_EL0_64 9
#define ENTRY_FIQ_INVALID_EL0_64 10
#define ENTRY_ERR_INVALID_EL0_64 11

#define ENTRY_SYN_INVALID_EL0_32 12
#define ENTRY_IRQ_INVALID_EL0_32 13
#define ENTRY_FIQ_INVALID_EL0_32 14
#define ENTRY_ERR_INVALID_EL0_32 15

#endif // !ASM_AARCH64_BOOT_ENTRY_H
