// Copyright (C) Dmytro Stechenko
// License: http://www.gnu.org/licenses/gpl.html

#ifndef ASM_MEMORY_DEFS_H
#define ASM_MEMORY_DEFS_H

#include <kernel/config.h>

#define CONCAT(a, b) a ## b
#define MEM(addr) CONCAT(addr, ull)

#define BOOT_LOAD_ADDRESS CONFIG_BOOT_LOAD_ADDRESS
#define VIRTUAL_MEMORY_OFFSET CONFIG_VIRTUAL_MEMORY_OFFSET

#define PHYSICAL_MEMORY_START MEM(CONFIG_PHYSICAL_MEMORY_START)
#define PHYSICAL_MEMORY_SIZE MEM(CONFIG_PHYSICAL_MEMORY_SIZE)
#define PHYSICAL_MEMORY_END (PHYSICAL_MEMORY_START + PHYSICAL_MEMORY_SIZE)

#define PHYSICAL_DEVICE_MEMORY_START MEM(CONFIG_PHYSICAL_DEVICE_MEMORY_START)
#define PHYSICAL_DEVICE_MEMORY_SIZE MEM(CONFIG_PHYSICAL_DEVICE_MEMORY_SIZE)
#define PHYSICAL_DEVICE_MEMORY_END (PHYSICAL_DEVICE_MEMORY_START + PHYSICAL_DEVICE_MEMORY_SIZE)

#endif // !ASM_MEMORY_DEFS_H
