// Copyright (C) Dmytro Stechenko
// License: http://www.gnu.org/licenses/gpl.html

#ifndef ASM_MEMORY_DEFS_H
#define ASM_MEMORY_DEFS_H

#include <kernel/config.h>

#ifndef __ASSEMBLER__
#include <kernel/types.h>
#endif // !__ASSEMBLER__

#define BOOT_LOAD_ADDRESS CONFIG_BOOT_LOAD_ADDRESS
#define VIRTUAL_MEMORY_OFFSET CONFIG_VIRTUAL_MEMORY_OFFSET

#ifndef __ASSEMBLER__
#define PHYSICAL_MEMORY_START TYPES_MEMORY(CONFIG_PHYSICAL_MEMORY_START)
#define PHYSICAL_MEMORY_SIZE TYPES_MEMORY(CONFIG_PHYSICAL_MEMORY_SIZE)
#define PHYSICAL_MEMORY_END (PHYSICAL_MEMORY_START + PHYSICAL_MEMORY_SIZE)
#define PHYSICAL_DEVICE_MEMORY_START TYPES_MEMORY(CONFIG_PHYSICAL_DEVICE_MEMORY_START)
#define PHYSICAL_DEVICE_MEMORY_SIZE TYPES_MEMORY(CONFIG_PHYSICAL_DEVICE_MEMORY_SIZE)
#define PHYSICAL_DEVICE_MEMORY_END (PHYSICAL_DEVICE_MEMORY_START + PHYSICAL_DEVICE_MEMORY_SIZE)
#define PHYSICAL_PERIPHERAL_MEMORY_START TYPES_MEMORY(CONFIG_PHYSICAL_PERIPHERAL_MEMORY_START)
#define PHYSICAL_PERIPHERAL_MEMORY_SIZE TYPES_MEMORY(CONFIG_PHYSICAL_PERIPHERAL_MEMORY_SIZE)
#define PHYSICAL_PERIPHERAL_MEMORY_END (PHYSICAL_PERIPHERAL_MEMORY_START + PHYSICAL_PERIPHERAL_MEMORY_SIZE)
#endif // !__ASSEMBLER__

#endif // !ASM_MEMORY_DEFS_H
