// Copyright (C) Dmytro Stechenko
// License: http://www.gnu.org/licenses/gpl.html

.globl atomic32_inc
.globl atomic32_dec
.globl atomic32_swp
.globl atomic32_cmp_swp

.globl atomic64_inc
.globl atomic64_dec
.globl atomic64_swp
.globl atomic64_cmp_swp

atomic32_inc:
  ret

atomic32_dec:
  ret

atomic32_swp:
  ret

atomic32_cmp_swp:
  ret

atomic64_inc:
  ret

atomic64_dec:
  ret

atomic64_swp:
  ret

atomic64_cmp_swp:
  ret
