// Copyright (C) Dmytro Stechenko
// License: http://www.gnu.org/licenses/gpl.html

#ifndef ARCH_AARCH64_ASM_MMU_DEFS_H
#define ARCH_AARCH64_ASM_MMU_DEFS_H

#include <kernel/bits.h>

#define MEMORY_TYPE_DEVICE 0x0
#define MEMORY_TYPE_DEVICE_FLAGS 0x0

#define MEMORY_TYPE_NORMAL 0x1
#define MEMORY_TYPE_NORMAL_FLAGS 0xFF

#define MAIR_TO_VALUE(flags, index) (flags << (8 * index))
#define MAIR_VALUE                                               \
  (MAIR_TO_VALUE(MEMORY_TYPE_DEVICE_FLAGS, MEMORY_TYPE_DEVICE) | \
   MAIR_TO_VALUE(MEMORY_TYPE_NORMAL_FLAGS, MEMORY_TYPE_NORMAL))

#define MMU_TYPE_PAGE_TABLE (BIT(0) | BIT(1))
#define MMU_TYPE_PAGE (BIT(0) | BIT(1))
#define MMU_TYPE_BLOCK (BIT(0) | NOBIT(1))

#define MMU_ACCESS BIT(10)
#define MMU_ACCESS_PERMISSION BIT(6)
#define MMU_SHAREABLE BIT(9)

#define MMU_USER_FLAGS \
  (MMU_TYPE_PAGE | (MEMORY_TYPE_NORMAL << 2) | MMU_ACCESS | MMU_ACCESS_PERMISSION | MMU_SHAREABLE)
#define MMU_KERNEL_FLAGS (MMU_TYPE_BLOCK | (MEMORY_TYPE_NORMAL << 2) | MMU_ACCESS | MMU_SHAREABLE)
#define MMU_DEVICE_FLAGS (MMU_TYPE_BLOCK | (MEMORY_TYPE_DEVICE << 2) | MMU_ACCESS | MMU_SHAREABLE)
#define MMU_KERNEL_PAGES_FLAGS (MMU_TYPE_PAGE | (MEMORY_TYPE_NORMAL << 2) | MMU_ACCESS | MMU_SHAREABLE)
#define MMU_DEVICE_PAGES_FLAGS (MMU_TYPE_PAGE | (MEMORY_TYPE_DEVICE << 2) | MMU_ACCESS | MMU_SHAREABLE)

#endif  // !ARCH_AARCH64_ASM_MMU_DEFS_H
